### ISSUE TITLE
Gitpod suggestions

### ISSUE THREAD

**Issue by chuck-alt-delete** [srinivasa-vasu/todo#1]
This is very cool! I have a suggestion. Go ahead and build and push the gitpod container image to a registry and reference that image in the .gitpod.yml file. Then add a “open in gitpod” link/button in your readme. That way, they user will be able to run this repo with a click of a button rather than forking and doing a bunch of manual setup first.

extra credit: enable prebuilds wherever the user is waiting on things that can be snapshotted.

cheers!

**Comment by chuck-alt-delete** [comment]
Looks like gitpod now recommends the Dockerfile approach using .gitpod.Dockerfile and the image will be built during prebuild. All the other suggestions still, though!

**Comment by srinivasa-vasu** [comment]
> Looks like gitpod now recommends the Dockerfile approach using .gitpod.Dockerfile and the image will be built during prebuild. All the other suggestions still, though!

.gitpodcontainer/Dockerfile is already in the repo and used. Not sure if you are referring to the same thing. Gitpod also has a browser extension that launches the container directly from the repo.
